AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  arxiv-citation-scanner

  An efficient, Lambda-based parallel citation info fetcher that reads a paper list from S3 and queries the OpenAlex API.

Parameters:
  ExistingDataBucketName:
    Type: String
    Description: The name of the existing S3 bucket where all data is stored.

Globals:
  Function:
    Runtime: python3.9
    MemorySize: 512
    Architectures:
      - x86_64

Resources:
  CitationJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CitationJobQueue
      VisibilityTimeout: 500
      MessageRetentionPeriod: 1209600

  CitationDispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/dispatcher_citation/
      Handler: citation_dispatcher_lambda.handler
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref CitationJobQueue
          S3_BUCKET_NAME: !Ref ExistingDataBucketName
          INPUT_S3_PREFIX: "cleaned_data/"
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ExistingDataBucketName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt CitationJobQueue.QueueName
        - Statement:
          - Effect: "Allow"
            Action: "lambda:InvokeFunction"
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-CitationDispatcherFunction-*"

  CitationWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/worker_citation/ # Requires requests library
      Handler: citation_worker_lambda.handler
      Timeout: 450
      ReservedConcurrentExecutions: 50
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref ExistingDataBucketName
          OPENALEX_EMAIL: "your-email@example.com"
      Policies:
        # --- FIX IS HERE: Changed S3WritePolicy to S3CrudPolicy ---
        # S3CrudPolicy grants permissions for Get, Put, and Delete actions.
        - S3CrudPolicy:
            BucketName: !Ref ExistingDataBucketName
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt CitationJobQueue.Arn
            BatchSize: 10

Outputs:
  S3BucketName:
    Description: "Name of the S3 bucket used for storing data"
    Value: !Ref ExistingDataBucketName
  CitationDispatcherFunctionName:
    Description: "Name of the Citation Dispatcher Lambda function"
    Value: !Ref CitationDispatcherFunction
