AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  arxiv-citation-scanner

  一個高效的、基於 Lambda 的論文引用資訊並行查詢器，從 S3 讀取論文列表，並使用 OpenAlex API 查詢數據。

Parameters:
  ExistingDataBucketName:
    Type: String
    Description: The name of the existing S3 bucket where all data is stored.

Globals:
  Function:
    Runtime: python3.9
    MemorySize: 512
    Architectures:
      - x86_64

Resources:
  CitationJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CitationJobQueue
      VisibilityTimeout: 500
      MessageRetentionPeriod: 1209600

  CitationDispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/dispatcher_citation/
      Handler: citation_dispatcher_lambda.handler
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref CitationJobQueue
          S3_BUCKET_NAME: !Ref ExistingDataBucketName
          INPUT_S3_PREFIX: "cleaned_data/"
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ExistingDataBucketName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt CitationJobQueue.QueueName
        - Statement:
          - Effect: "Allow"
            Action: "lambda:InvokeFunction"
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-CitationDispatcherFunction-*"

  CitationWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/worker_citation/ # Requires requests library
      Handler: citation_worker_lambda.handler
      Timeout: 450
      ReservedConcurrentExecutions: 50
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref ExistingDataBucketName
          OPENALEX_EMAIL: "your-email@example.com"
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ExistingDataBucketName
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt CitationJobQueue.Arn
            BatchSize: 10

Outputs:
  S3BucketName:
    Description: "儲存所有數據的 S3 儲存桶名稱"
    Value: !Ref ExistingDataBucketName
  CitationDispatcherFunctionName:
    Description: "引用查詢分派器 Lambda 名稱"
    Value: !Ref CitationDispatcherFunction
