AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  arxiv-citation-scanner
  從既有 S3 Bucket 讀取論文列表，並行查詢 Semantic Scholar 引用資訊

Parameters:
  ExistingDataBucketName:
    Type: String
    Description: Name of the **existing** S3 bucket that stores paper data
    Default: arxiv-dataset-376926525020-us-east-1

Globals:
  Function:
    Runtime: python3.9
    MemorySize: 512
    Architectures:
      - x86_64

Resources:
  # ---- SQS 隊列 ----
  CitationJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CitationJobQueue
      VisibilityTimeout: 500
      MessageRetentionPeriod: 1209600   # 14 天

  # ---- Dispatcher Lambda ----
  CitationDispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/dispatcher_citation/
      Handler: citation_dispatcher_lambda.handler
      Timeout: 900
      MemorySize: 2048
      EphemeralStorage:
        Size: 2048
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref CitationJobQueue
          S3_BUCKET_NAME: !Ref ExistingDataBucketName
      Policies:
        - S3ReadPolicy:        # 讀 S3 上的論文 CSV
            BucketName: !Ref ExistingDataBucketName
        - SQSSendMessagePolicy: # 發送訊息到隊列
            QueueName: CitationJobQueue

  # ---- Worker Lambda ----
  CitationWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/worker_citation/
      Handler: citation_worker_lambda.handler
      Timeout: 450
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref ExistingDataBucketName
      Policies:
        - S3WritePolicy:       # 寫回查詢結果
            BucketName: !Ref ExistingDataBucketName
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt CitationJobQueue.Arn
            BatchSize: 1

Outputs:
  DataBucketName:
    Description: "Existing S3 Bucket used for paper data"
    Value: !Ref ExistingDataBucketName

  CitationDispatcherFunctionName:
    Description: "Dispatcher Lambda Function name"
    Value: !Ref CitationDispatcherFunction
